version: '3'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    platform: linux/amd64
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870"
      - "8020:8020"
    volumes:
      - ./data/hadoop/namenode:/hadoop/dfs/name
      # - ./data/my-hadoop-conf/namenode:/etc/hadoop/conf
    networks:
      - hadoop

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    platform: linux/amd64
    hostname: datanode1
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      - namenode
    volumes:
      - ./data/hadoop/datanode1:/hadoop/dfs/data
      # - ./data/my-hadoop-conf/datanode1:/etc/hadoop/conf
    networks:
      - hadoop

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    platform: linux/amd64
    hostname: datanode2
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      - namenode
    volumes:
      - ./data/hadoop/datanode2:/hadoop/dfs/data
      # - ./data/my-hadoop-conf/datanode2:/etc/hadoop/conf
    networks:
      - hadoop


networks:
  hadoop:
 

